### ISSUE TITLE
New game when going back to view 2 and start again?

### ISSUE THREAD

**Issue by Martin36** [Martin36/LastShipStanding#11]

**Comment by Eldhen** [comment]
fixar det nu

**Comment by Eldhen** [comment]
Behöver ändra removePlayer i model och använda det i controller :)

**Comment by Martin36** [comment]
Det läggs typ till en båt när man går tillbaka till play

**Comment by Martin36** [comment]
Vad ska removePlayer göra?

**Comment by Eldhen** [comment]
Redan fixat du kan stänga ner tråden
