### ISSUE TITLE
Sound! (Controller & Model )

### ISSUE THREAD

**Issue by pjheden** [Martin36/LastShipStanding#9]
- [x] Sound files
- [x] var audio = new Audio('src.mp3'); in Model
- [x] audio.play(); in Controller

**Comment by Martin36** [comment]
Ska Audio vara en klass?

**Comment by pjheden** [comment]
Nej behövs inte tycker jag, är så få rader kod som behövs.
Kan bara göra en audio variabel för players/model och environment och en getAudio

**Comment by Martin36** [comment]
Så, audio variabeln lagras i player och canonball klasserna etc. inte i model?

**Comment by pjheden** [comment]
hmm, inte helt säker men här är några förslag::
Background / water music - environment
Shoot - model? eftersom man skjuter där
Ship sink sound - model? eller kanske player, säg om det ska bero på båt elr något
player winner audio - player (om man ska ha en taunt ljud som får väljas och spelas upp om man vinner ronden )

**Comment by Martin36** [comment]
Låter bra det. Eller så kör jag bara allt i modellen och döper de till typ environmentAudio etc.
